settings:
  title: 'Uptime Durum Takip'
  url: 'https://cf-workers-status-page-production.bugra.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Bütün Servisler Çalışıyor'
  notAllmonitorsOperational: 'Bütün Servisler Çalışmıyor'
  monitorLabelOperational: 'Çalışıyor'
  monitorLabelNotOperational: 'Çalışmıyor'
  monitorLabelNoData: 'Veri yok'
  dayInHistogramNoData: 'Veri yok'
  dayInHistogramOperational: 'Sorun yok'
  dayInHistogramNotOperational: ' olay' # xx incident(s) recorded

monitors:
  - id: bugracanata.com.tr # unique identifier
    name: bugracanata.com.tr
    description: 'kişisel sayfam' # default=empty
    url: 'https://bugracanata.com.tr/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ayseerkan.com
    name: ayseerkan.com
    description: 'okul sitesi'
    url: 'https://ayseerkan.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: notlar.im
    name: notlar.im
    description: 'blogum'
    url: 'https://notlar.im'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
